name: Process logging

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    name: Process logging
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    env:
      SUPABASE_PASS: ${{secrets.SUPABASE_PASS}}
      SUPABASE_HOST: ${{secrets.SUPABASE_HOST}}
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.13'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pandas==1.2.0 numpy==1.19.5 requests==2.28.1 urllib3==1.26.12 typer==0.6.1 psycopg2==2.9.7 python-decouple==3.6 pytest==7.1.3 supabase==0.7.1
    - name: Build data
      run: |
        python3 analize_xnft.py
